/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package martian;

import javax.swing.JOptionPane;

/**
 *
 * @author erikbv99421
 */
public class Visual extends javax.swing.JFrame implements Runnable {

    public int min_ = 0, seg_ = 0;
    Thread hilo_;

    /**
     * Creates new form Visual
     */
    public Visual() {
        initComponents();
        Grupo.add(robotButton);
        Grupo.add(estacionButton);
        Grupo.add(obstaculoButton);
        hilo_ = new Thread(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo = new javax.swing.JPanel();
        robotButton = new javax.swing.JRadioButton();
        estacionButton = new javax.swing.JRadioButton();
        obstaculoButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cronometro = new javax.swing.JLabel();
        resolverMaloButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        lienzo1 = new martian.Lienzo();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Resolver = new javax.swing.JMenuItem();
        mapaAleatorio = new javax.swing.JMenuItem();
        reiniciar = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        acerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Grupo.setBorder(javax.swing.BorderFactory.createTitledBorder("Herramientas"));

        robotButton.setText("ROBOT");
        robotButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                robotButtonMouseClicked(evt);
            }
        });
        robotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                robotButtonActionPerformed(evt);
            }
        });

        estacionButton.setText("ESTACION");
        estacionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estacionButtonMouseClicked(evt);
            }
        });

        obstaculoButton.setText("OBSTÁCULO");
        obstaculoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                obstaculoButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout GrupoLayout = new javax.swing.GroupLayout(Grupo);
        Grupo.setLayout(GrupoLayout);
        GrupoLayout.setHorizontalGroup(
            GrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GrupoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estacionButton)
                    .addComponent(robotButton)
                    .addComponent(obstaculoButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GrupoLayout.setVerticalGroup(
            GrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GrupoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(robotButton)
                .addGap(18, 18, 18)
                .addComponent(estacionButton)
                .addGap(18, 18, 18)
                .addComponent(obstaculoButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/martian/images/cronometro.png"))); // NOI18N
        jLabel1.setText("Tiempo");

        cronometro.setText("0'   0''");

        resolverMaloButton.setText("Resolver Malo");
        resolverMaloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resolverMaloButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Resolver A*");

        jButton3.setText("Resolver Primero el mejor");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Práctica de Inteligencia Artificial. Grado en Ingeniería Informática, Universidad de la Laguna.\n\nBienvenidos al programa de resolución de laberintos mediante algoritmos de busquedas.\nInstrucciones modo manual:\n\n\t1) Selecciona la opción que desea dibujar en el panel de herramientas, ubicado en la parte superior derecha.\n\t2) Presione el botón de resolver con el algoritmo deseado.\n\t3) Una vez finalizado puede usar la opción del menú reiniciar para reestablecer los ajustes iniciales.\n\nInstrucciones modo Aleatorio:\n\n\t1) Selecciona la opción del menú generar mapa aleatorio.\n\t2) Presione el botón de resolver con el algoritmo deseado.\n\t3) Una vez finalizado puede usar la opción del menú reiniciar para reestablecer los ajustes iniciales.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/martian/images/info.png"))); // NOI18N
        jLabel3.setText("Información");

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        jMenu1.setText("Opciones");

        Resolver.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        Resolver.setText("Resolver");
        Resolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResolverActionPerformed(evt);
            }
        });
        jMenu1.add(Resolver);

        mapaAleatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mapaAleatorio.setText("Generar Mapa Aleatorio");
        mapaAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapaAleatorioActionPerformed(evt);
            }
        });
        jMenu1.add(mapaAleatorio);

        reiniciar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        reiniciar.setText("Reiniciar");
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });
        jMenu1.add(reiniciar);

        salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu1.add(salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Equipo Martian");

        acerca.setText("Acerca del equipo Martian");
        acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaActionPerformed(evt);
            }
        });
        jMenu2.add(acerca);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cronometro)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Grupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(resolverMaloButton)
                                            .addComponent(jButton3)
                                            .addComponent(jButton2))
                                        .addGap(0, 326, Short.MAX_VALUE)))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cronometro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resolverMaloButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResolverActionPerformed

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        // TODO add your handling code here:
        lienzo1.hilo_.stop();
        lienzo1.restart();
        hilo_ = new Thread(this);
        resolverMaloButton.setEnabled(true);
        Resolver.setEnabled(true);
        min_ = 0;
        seg_ = 0;
        cronometro.setText( min_ + "'   " + seg_ + "''" );
        
    }//GEN-LAST:event_reiniciarActionPerformed

    private void acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acercaActionPerformed

    private void robotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_robotButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_robotButtonActionPerformed

    private void resolverMaloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resolverMaloButtonActionPerformed
        // TODO add your handling code here:
        try {
            lienzo1.hilo_.start();
            resolverMaloButton.setEnabled(false);
            Resolver.setEnabled(false);
            lienzo1.f_=2;
            hilo_.start();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ocurrió un error: " + e.getMessage());
        }
    }//GEN-LAST:event_resolverMaloButtonActionPerformed

    private void robotButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robotButtonMouseClicked
        // TODO add your handling code here:
        if (robotButton.isSelected()) {
            lienzo1.radioButtons_=3;
        }
    }//GEN-LAST:event_robotButtonMouseClicked

    private void estacionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estacionButtonMouseClicked
        // TODO add your handling code here:
        if (robotButton.isSelected()) {
            lienzo1.radioButtons_=2;
        }
    }//GEN-LAST:event_estacionButtonMouseClicked

    private void obstaculoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_obstaculoButtonMouseClicked
        // TODO add your handling code here:
        if (robotButton.isSelected()) {
            lienzo1.radioButtons_=1;
        }
    }//GEN-LAST:event_obstaculoButtonMouseClicked

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void mapaAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapaAleatorioActionPerformed
        // TODO add your handling code here:
        lienzo1.RandomMap();
    }//GEN-LAST:event_mapaAleatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Grupo;
    private javax.swing.JMenuItem Resolver;
    private javax.swing.JMenuItem acerca;
    private javax.swing.JLabel cronometro;
    private javax.swing.JRadioButton estacionButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private martian.Lienzo lienzo1;
    private javax.swing.JMenuItem mapaAleatorio;
    private javax.swing.JRadioButton obstaculoButton;
    private javax.swing.JMenuItem reiniciar;
    private javax.swing.JButton resolverMaloButton;
    private javax.swing.JRadioButton robotButton;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {            
            try {
                Thread.sleep(999);
                seg_++;
                if (seg_ >= 59) {
                    min_++;
                    seg_=0;
                }
                cronometro.setText(min_ + "'   " + seg_ + "''" );
                if (lienzo1.isFinished == 1) {
                    hilo_.stop();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ocurrió un error: " + e.getMessage());
            }
        }
    }
}
