/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package martian;

import javax.swing.JOptionPane;

/**
 *
 * @author erikbv99421
 */
public class Visual extends javax.swing.JFrame implements Runnable {

    public int min_ = 0, seg_ = 0;
    Thread hilo_;

    /**
     * Creates new form Visual
     */
    public Visual() {
        initComponents();
        grupo.add(robotButton);
        grupo.add(estacionButton);
        grupo.add(obstaculoButton);
        acercaJF.pack();
        hilo_ = new Thread(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        acercaJF = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        cerrarAbout = new javax.swing.JButton();
        jFrame1 = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        Grupo = new javax.swing.JPanel();
        robotButton = new javax.swing.JRadioButton();
        estacionButton = new javax.swing.JRadioButton();
        obstaculoButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cronometro = new javax.swing.JLabel();
        resolverMaloButton = new javax.swing.JButton();
        AEstrellaButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        columnas_ = new javax.swing.JTextField();
        filas_ = new javax.swing.JTextField();
        generarMatrix_ = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        porce_ = new javax.swing.JTextField();
        lienzo1 = new martian.Lienzo();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Resolver = new javax.swing.JMenuItem();
        mapaAleatorio = new javax.swing.JMenuItem();
        reiniciar = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        acerca = new javax.swing.JMenuItem();

        jLabel2.setText("Acerca de la práctica");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Práctica de Inteligencia Artificial\nIngeniería Informática\nUniversidad de la Laguna\nTenerife - España\nIntegrantes:\nErik Barreto de Vera\nJosé Joaquín Escobar Góimez");
        jScrollPane2.setViewportView(jTextArea2);

        cerrarAbout.setText("Cerrar");
        cerrarAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarAboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout acercaJFLayout = new javax.swing.GroupLayout(acercaJF.getContentPane());
        acercaJF.getContentPane().setLayout(acercaJFLayout);
        acercaJFLayout.setHorizontalGroup(
            acercaJFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acercaJFLayout.createSequentialGroup()
                .addGroup(acercaJFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(acercaJFLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2))
                    .addGroup(acercaJFLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(cerrarAbout))
                    .addGroup(acercaJFLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        acercaJFLayout.setVerticalGroup(
            acercaJFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acercaJFLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(cerrarAbout)
                .addContainerGap())
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Grupo.setBorder(javax.swing.BorderFactory.createTitledBorder("Herramientas"));

        robotButton.setText("ROBOT");
        robotButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                robotButtonMouseClicked(evt);
            }
        });
        robotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                robotButtonActionPerformed(evt);
            }
        });

        estacionButton.setText("ESTACION");
        estacionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estacionButtonMouseClicked(evt);
            }
        });

        obstaculoButton.setText("OBSTÁCULO");
        obstaculoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                obstaculoButtonMouseClicked(evt);
            }
        });
        obstaculoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obstaculoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GrupoLayout = new javax.swing.GroupLayout(Grupo);
        Grupo.setLayout(GrupoLayout);
        GrupoLayout.setHorizontalGroup(
            GrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GrupoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estacionButton)
                    .addComponent(robotButton)
                    .addComponent(obstaculoButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GrupoLayout.setVerticalGroup(
            GrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GrupoLayout.createSequentialGroup()
                .addComponent(obstaculoButton)
                .addGap(12, 12, 12)
                .addComponent(robotButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(estacionButton))
        );

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/martian/images/cronometro.png"))); // NOI18N
        jLabel1.setText("Tiempo");

        cronometro.setText("0'   0''");

        resolverMaloButton.setText("Resolver Malo");
        resolverMaloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resolverMaloButtonActionPerformed(evt);
            }
        });

        AEstrellaButton.setText("Resolver A*");
        AEstrellaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEstrellaButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Resolver Primero el mejor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Práctica de Inteligencia Artificial. Grado en Ingeniería Informática, Universidad de la Laguna.\n\nBienvenidos al programa de resolución de laberintos mediante algoritmos de busquedas.\nInstrucciones modo manual:\n\n\t1) Selecciona la opción que desea dibujar en el panel de herramientas, ubicado en la parte superior derecha.\n\t2) Presione el botón de resolver con el algoritmo deseado.\n\t3) Una vez finalizado puede usar la opción del menú reiniciar para reestablecer los ajustes iniciales.\n\nInstrucciones modo Aleatorio:\n\n\t1) Selecciona la opción del menú generar mapa aleatorio.\n\t2) Presione el botón de resolver con el algoritmo deseado.\n\t3) Una vez finalizado puede usar la opción del menú reiniciar para reestablecer los ajustes iniciales.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/martian/images/info.png"))); // NOI18N
        jLabel3.setText("Información");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tamaño"));

        jLabel5.setText("# Columnas :");

        jLabel6.setText("# Filas :");

        columnas_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnas_ActionPerformed(evt);
            }
        });

        generarMatrix_.setText("Crear");
        generarMatrix_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarMatrix_ActionPerformed(evt);
            }
        });

        jLabel7.setText("% Obstaculos: ");

        porce_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porce_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(porce_, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(filas_)
                            .addComponent(columnas_)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(generarMatrix_)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(columnas_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filas_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(porce_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(generarMatrix_))
        );

        lienzo1.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jMenu1.setText("Opciones");

        Resolver.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        Resolver.setText("Resolver");
        Resolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResolverActionPerformed(evt);
            }
        });
        jMenu1.add(Resolver);

        mapaAleatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mapaAleatorio.setText("Generar Mapa Aleatorio");
        mapaAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapaAleatorioActionPerformed(evt);
            }
        });
        jMenu1.add(mapaAleatorio);

        reiniciar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        reiniciar.setText("Reiniciar");
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });
        jMenu1.add(reiniciar);

        salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu1.add(salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Equipo Martian");

        acerca.setText("Acerca del equipo Martian");
        acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaActionPerformed(evt);
            }
        });
        jMenu2.add(acerca);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cronometro)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Grupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(resolverMaloButton)
                                            .addComponent(jButton3)
                                            .addComponent(AEstrellaButton))
                                        .addGap(0, 33, Short.MAX_VALUE))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cronometro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AEstrellaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resolverMaloButton))
                    .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResolverActionPerformed

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        // TODO add your handling code here:
        lienzo1.hilo_.stop();
        //JOptionPane.showMessageDialog(this, "si desea cargar mapa por defecto introduzca numero de filas y columnas a cero");
        String aux1 = JOptionPane.showInputDialog(this, "Introducir numero de filas:");
        int f = Integer.parseInt(aux1);
        String aux2 = JOptionPane.showInputDialog(this, "Introducir numero de columnas:");
        int c = Integer.parseInt(aux2);
        lienzo1.restart(f,c);
        hilo_ = new Thread(this);
        //lienzo1.hilo_.start();
        resolverMaloButton.setEnabled(true);
        AEstrellaButton.setEnabled(true);
        Resolver.setEnabled(true);
        min_ = 0;
        seg_ = 0;
        cronometro.setText( min_ + "'   " + seg_ + "''" );
        
    }//GEN-LAST:event_reiniciarActionPerformed

    private void acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaActionPerformed
        // TODO add your handling code here:
        acercaJF.setVisible(true);
    }//GEN-LAST:event_acercaActionPerformed

    private void robotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_robotButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_robotButtonActionPerformed

    private void resolverMaloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resolverMaloButtonActionPerformed
        // TODO add your handling code here:
        try {
            lienzo1.hilo_.start();
            resolverMaloButton.setEnabled(false);
            Resolver.setEnabled(false);
            lienzo1.f_=2;
            hilo_.start();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ocurrió un error: " + e.getMessage());
        }
    }//GEN-LAST:event_resolverMaloButtonActionPerformed

    private void robotButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_robotButtonMouseClicked
        // TODO add your handling code here:
        if (robotButton.isSelected()) {
            lienzo1.radioButtons_=2;
        }
    }//GEN-LAST:event_robotButtonMouseClicked

    private void estacionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estacionButtonMouseClicked
        // TODO add your handling code here:
        if (estacionButton.isSelected()) {
            lienzo1.radioButtons_=3;
        }
    }//GEN-LAST:event_estacionButtonMouseClicked

    private void obstaculoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_obstaculoButtonMouseClicked
        // TODO add your handling code here:
        if (obstaculoButton.isSelected()) {
            lienzo1.radioButtons_=1;
        }
    }//GEN-LAST:event_obstaculoButtonMouseClicked

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void mapaAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapaAleatorioActionPerformed
        // TODO add your handling code here:
        lienzo1.RandomMap();
    }//GEN-LAST:event_mapaAleatorioActionPerformed

    private void obstaculoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obstaculoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obstaculoButtonActionPerformed


    private void cerrarAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarAboutActionPerformed
        // TODO add your handling code here:
        acercaJF.setVisible(false);
    }//GEN-LAST:event_cerrarAboutActionPerformed

    private void columnas_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnas_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_columnas_ActionPerformed

    private void AEstrellaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEstrellaButtonActionPerformed
        // TODO add your handling code here:
        try {
            lienzo1.hilo_.start();
            AEstrellaButton.setEnabled(false);
            Resolver.setEnabled(false);
            lienzo1.f_=2;
            hilo_.start();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ocurrió un error: " + e.getMessage());
        }
    }//GEN-LAST:event_AEstrellaButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void porce_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porce_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_porce_ActionPerformed

    private void generarMatrix_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarMatrix_ActionPerformed
        // TODO add your handling code here:
        //JTextField f1 = new JTextField("-5");
        //String text = f1.getText();
        //int xaxis1 = Integer.parseInt(text);
        String stringFilas_ = filas_.getText();
        String stringColumnas_ = columnas_.getText();
        String stringPorce_ = porce_.getText();
        int numFilas_ = Integer.parseInt(stringFilas_);
        int numColumnas_ = Integer.parseInt(stringColumnas_);
        int numPorce_ = Integer.parseInt(stringPorce_);
        //lienzo1.ManualMap(numFilas_,numColumnas_,numPorce_);
    }//GEN-LAST:event_generarMatrix_ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AEstrellaButton;
    private javax.swing.JPanel Grupo;
    private javax.swing.JMenuItem Resolver;
    private javax.swing.JMenuItem acerca;
    private javax.swing.JFrame acercaJF;
    private javax.swing.JButton cerrarAbout;
    private javax.swing.JTextField columnas_;
    private javax.swing.JLabel cronometro;
    private javax.swing.JRadioButton estacionButton;
    private javax.swing.JTextField filas_;
    private javax.swing.JButton generarMatrix_;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private martian.Lienzo lienzo1;
    private javax.swing.JMenuItem mapaAleatorio;
    private javax.swing.JRadioButton obstaculoButton;
    private javax.swing.JTextField porce_;
    private javax.swing.JMenuItem reiniciar;
    private javax.swing.JButton resolverMaloButton;
    private javax.swing.JRadioButton robotButton;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {            
            try {
                Thread.sleep(999);
                seg_++;
                if (seg_ >= 59) {
                    min_++;
                    seg_=0;
                }
                cronometro.setText(min_ + "'   " + seg_ + "''" );
                if (lienzo1.isFinished == 1) {
                    hilo_.stop();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ocurrió un error: " + e.getMessage());
            }
        }
    }
}
